### ISSUE TITLE
Versioning scheme (2.2 > 2.11)

### ISSUE THREAD

**Issue by tomyun** [eighttails/PC6001VX#1] opened 2016-04-28 07:30 UTC
I just noticed a new release and congratulations.

By the way, there's a chance that the new version (2.2) perceived older than the previous version (2.11) since 2 is numerically lower than 11. Considering many package managers, including [Homebrew](https://github.com/Homebrew/homebrew-games/blob/master/pc6001vx.rb), follow numerical comparison rather than lexical, we'd better not make unnecessary confusion here. [Semantic versioning](http://semver.org) might be a good reference.

**Comment by eighttails** [comment] 2016-04-30 12:17
Hi,tomyun.
Thanks for your advice.
According to your advice, the next bug-fix release should be 2.2.1 instead of 2.21, right?
I haven't had definite versioning policy so adopting Semantic versioning is a good idea.

However, I think the problem is that version 2.11 already exists.
Do I have to keep consistency with all versions older than 2.2?

**Comment by tomyun** [comment] 2016-05-01 20:57
Yes, for the next bug-fix release, 2.2.1 after 2.2 sounds better than 2.21 after 2.2.

Well, it may be hard, if not impossible, to change already released versions. One option you could consider is to re-release the latest version as 2.12, not 2.2, to keep consistent with previous releases. Then the following version would be 2.12.1 or 2.13 or 3.0 depending on the updates.

**Comment by eighttails** [comment] 2016-05-02 16:08
If I name next version 2.21.0, would it be recognized as newer than both 2.2 and 2.11?

**Comment by tomyun** [comment] 2016-05-02 19:15
Yes, it would.

**Comment by eighttails** [comment] 2016-05-04 14:53
I have released 2.21.0.
Closing issue.

**Closed as completed by eighttails** 2016-05-04 14:53 UTC
